### ISSUE TITLE
HikariJdbcObservationFilter fails with NPE when getConnection failed

### ISSUE THREAD

**Issue by ttddyy** [jdbc-observations/datasource-micrometer#44]
See the background in https://github.com/jdbc-observations/datasource-micrometer/issues/40#issuecomment-2200590308

cc @luispflamminger

**Comment by ttddyy** [comment]
@luispflamminger I added a commit to fix this issue.

Can you try `1.0.5-SNAPSHOT` to confirm it works in your environment?
It is published to the OSS sonatype snapshot repository.
Quick configuration for using the snapshot repo is in https://github.com/jdbc-observations/datasource-micrometer#using-snapshot

Thanks!!

**Comment by luispflamminger** [comment]
Can confirm it fixes the issue.
@ttddyy Thanks for the quick help!
