### ISSUE TITLE
Question: how to add `jdbc.query` to metric tags

### ISSUE THREAD

**Issue by superxiao** [jdbc-observations/datasource-micrometer#47]
When manually building a micrometer Timer sample, I could do something like this:
```java
    Timer.Sample sample = Timer.start(meterRegistry);
    try {
      return invocation.proceed();
    } finally {
      String sql = ...;
      sample.stop(Timer.builder("db.query")
          .tag("sql", sql)
          .register(meterRegistry));
    }
```

Then on the visualization side I would be able to sort DB metrics by SQL query. Is it possible to do this with datasource-micrometer metrics?

**Comment by ttddyy** [comment]
Hi @superxiao 

Yes, that's essentially how query observation works.
The observation starts just before the query execution and stops right after the completion.
The `DefaultMeterObservationHandler` in Micrometer creates timers around it. So, metrics are generated for the query execution.

**Comment by superxiao** [comment]
Hi @ttddyy , thanks for the explanation. I'm wondering whether it's possible to add the sql query string as a prometheus/grafana label, to be available in this list?
<img width="657" alt="image" src="https://github.com/user-attachments/assets/df86c51f-aac3-4a06-8e99-c84239bf4e57">

Using the manual Timer creation, the `.tag("sql", sql)` call would do that and allow creating charts that shows metrics sorted by sql string, something like the following.

<img width="738" alt="image" src="https://github.com/user-attachments/assets/1d7297a3-c3cb-46df-8964-1f4dbeced492">

**Comment by ttddyy** [comment]
In the `DefaultMeterObservationHandler`, low cardinality keys are tagged to metrics.
However, query is not low cardinality, it is a high cardinality key-value.
So, it won't be added to a metrics tags.

If you really want to add queries to metrics tags, you may write an `ObservationFilter` that adds a high-cardinality key from the query low-cardinality key. But again, please be aware you may have an issue with sending high cardinality data to the backend.
https://develotters.com/posts/high-cardinality/

**Comment by superxiao** [comment]
Makes sense. I have been using the manual `.tag("sql", sql)` to create bar charts on slow queries, and although it's super useful for query optimization, it does lead to high resource usage from prometheus.
Knowing I can do something similar in `datasource-micrometer` is great, and I will probably only attatch the tag of sql string when the query is slow, when using `datasource-micrometer` metrics to replace my custom ones, in order to cut down cardinality.

**Comment by jbaris** [comment]
For those who need the same, this code (based on @ttddyy comment) works for me:

```
import io.micrometer.common.KeyValue;
import io.micrometer.observation.Observation;
import io.micrometer.observation.ObservationFilter;
import org.springframework.stereotype.Component;

@Component
public class CustomQueryObservationFilter implements ObservationFilter {

    @Override
    public Observation.Context map(Observation.Context context) {
        if("jdbc.query".equals(context.getName())) {
            final KeyValue queryKeyValue = context.getHighCardinalityKeyValue("jdbc.query[0]");
            final KeyValue newKeyValue = KeyValue.of("jdbc.query", queryKeyValue.getValue());
            context.addLowCardinalityKeyValue(newKeyValue);
        }
        return context;
    }

}
```
Hope it helps.
