### ISSUE TITLE
Question: Spring Boot Auto Configuration

### ISSUE THREAD

**Issue by sethtomy** [jdbc-observations/datasource-micrometer#48]
I'm attempting to get spans for my db queries using this library on a relatively bare bones project. I have the following dependencies in my pom.xml:

* Spring Boot 3.3.4
* Datasource Micrometer Spring Boot 1.0.5

I've read through the [documentation](https://jdbc-observations.github.io/datasource-micrometer/docs/current/docs/html/) and I think including the dependency out of the box should work out of the box but I'm not seeing the JDBC spans in Jaeger. I tried a couple of the application.properties logging options with no luck either.

Are there any manual configuration steps or debugging tips?

If needed I can provide a minimal reproduction repo.

**Comment by ttddyy** [comment]
Yes, it should be pretty much out of the box experience. It instruments the `DataSource` bean. Are you exposing your `DataSource` as a bean?
Also, I suspect the sampling setting may be preventing the creation of spans.

Please check those, and if it still does not work, minimal repro is helpful.

**Comment by sethtomy** [comment]
@ttddyy thank you for the quick response.

It turns out in creating the minimal repro I've discovered it may have been a caching issue with IntelliJ. Thank you for your time and the cool library!
