### ISSUE TITLE
Question : How to get slow query metrics in milliseconds instead of seconds

### ISSUE THREAD

**Issue by rajadilipkolli** [jdbc-observations/datasource-micrometer#49]
Currently, all metrics are based on seconds. We have a requirement to get them in milli seconds. is it possible to get them in milli seconds?

**Comment by ttddyy** [comment]
Metrics from observations are created by `DefaultMeterObservationHandler` in the micrometer.
They are `LongTaskTimer` and `Timer`.
The resolution of the timers is based on the metrics backend.
So, please check with your backend and your micrometer registry.
