### ISSUE TITLE
Multiple datasources not managed

### ISSUE THREAD

**Issue by hankerspace** [jdbc-observations/datasource-micrometer#50]
Hello,

It looks like multiple datasource are not managed by this lib. 
Since you rely on the default "spring.datasource" configuration, it appears only the main datasource is successfully monitored.

 In our case we have muultiple datasources and we do not use "spring.datasource" configuration keys but "XX.datasource", "YY.datasource" keys.

Multiple datasources are programatically managed by configuration classes and beans.

Is there a way to configure this plugin to deal with these datasources or it is not possible by design?

Thanks

**Comment by ttddyy** [comment]
The [DataSourceObservationBeanPostProcessor](https://github.com/jdbc-observations/datasource-micrometer/blob/main/datasource-micrometer-spring-boot/src/main/java/net/ttddyy/observation/boot/autoconfigure/DataSourceObservationBeanPostProcessor.java#L85-L98) wraps `DataSource` beans with observation-aware datasources.

As long as each `DataSource` is defined as a bean — whether it's a single or multiple datasource — all datasource beans are automatically converted, regardless of whether they're created by `spring.datasource.*`, `XX.datasource`, or any other ways.

Please check that your datasources are defined as beans, and consider setting a breakpoint in `DataSourceObservationBeanPostProcessor` to confirm they’re being processed.
